import dotenv from 'dotenv';
dotenv.config();
import mongoose from 'mongoose';
import Contact from './models/Contact.js';
import Location from './models/Location.js';

// Realistic Indian Names
const firstNames = ['Aarav', 'Vihaan', 'Aditya', 'Arjun', 'Sai', 'Rohan', 'Krishna', 'Ishaan', 'Shaurya', 'Atharv', 'Diya', 'Ananya', 'Saanvi', 'Aditi', 'Isha', 'Kavya', 'Avni', 'Neha', 'Riya', 'Priya', 'Rahul', 'Amit', 'Vikram', 'Sanjay', 'Raj', 'Pooja', 'Sneha', 'Anita', 'Sunita', 'Rekha'];
const lastNames = ['Patel', 'Shah', 'Desai', 'Mehta', 'Suthar', 'Sharma', 'Verma', 'Singh', 'Kumar', 'Gupta', 'Joshi', 'Chauhan', 'Trivedi', 'Bhatt', 'Rathod', 'Parmar', 'Solanki', 'Chavda', 'Gohil', 'Jadeja'];

// Realistic Categories & Relations
const categories = ['VIP', 'Business', 'Family', 'Friend', 'Vendor', 'Colleague', 'Community Member', 'Donor'];
const relations = ['Brother', 'Sister', 'Father', 'Mother', 'Uncle', 'Aunt', 'Cousin', 'Friend', 'Business Partner'];
const honorifics = ['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.'];
const mandals = ['North Zone Mandal', 'South Zone Mandal', 'East Zone Mandal', 'West Zone Mandal'];

// Realistic Geographic Hierarchy
const geoHierarchy = {
    'Gujarat': {
        'Ahmedabad': ['Maninagar', 'Navrangpura', 'Vastrapur', 'Bopal', 'Satellite'],
        'Surat': ['Adajan', 'Vesu', 'Varachha', 'Piplod', 'Katargam'],
        'Vadodara': ['Alkapuri', 'Karelibaug', 'Makarpura', 'Sayajigunj', 'Gorwa'],
        'Rajkot': ['Kalawad Road', 'University Road', 'Amin Marg', 'Raiya Road']
    },
    'Maharashtra': {
        'Mumbai': ['Andheri', 'Bandra', 'Borivali', 'Dadar', 'Juhu'],
        'Pune': ['Kothrud', 'Viman Nagar', 'Hinjewadi', 'Baner', 'Kalyani Nagar']
    }
};

const getRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];
const getRandomPhone = () => {
    let phone = '9'; // Indian mobile usually starts with 9, 8, 7, 6
    for(let i = 0; i < 9; i++) {
        phone += Math.floor(Math.random() * 10);
    }
    return phone;
};

async function seedContacts() {
    const uri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/chevera_db';
    console.log('Connecting to MongoDB...');
    await mongoose.connect(uri);
    console.log('Connected.\n');

    console.log('1. Setting up Location Data...');
    const locationMapping = [];

    // Ensure our realistic geographic hierarchy is in the Location collection
    for (const [stateName, districts] of Object.entries(geoHierarchy)) {
        let stateDoc = await Location.findOne({ state: new RegExp('^' + stateName + '$', 'i') });
        if (!stateDoc) {
            stateDoc = new Location({ state: stateName, districts: [] });
        }

        for (const [districtName, cities] of Object.entries(districts)) {
            let distObj = stateDoc.districts.find(d => d.name.toLowerCase() === districtName.toLowerCase());
            if (!distObj) {
                distObj = { name: districtName, cities: [] };
                stateDoc.districts.push(distObj);
            }

            for (const cityName of cities) {
                if (!distObj.cities.some(c => c.toLowerCase() === cityName.toLowerCase())) {
                    distObj.cities.push(cityName);
                }
                // Save this valid combination to be picked by our random generator
                locationMapping.push({
                    state: stateName,
                    district: districtName,
                    city: cityName
                });
            }
        }
        await stateDoc.save();
    }
    console.log(`✅ Geographic data synced. Found ${locationMapping.length} valid distinct locations.\n`);

    console.log('2. Generating 250 Contacts...');
    // We will clear existing contacts first so the DB is perfectly clean and aligned
    await Contact.deleteMany({});
    console.log('✅ Cleared old contacts.');

    const newContacts = [];
    for (let i = 0; i < 250; i++) {
        const loc = getRandom(locationMapping);
        const contact = {
            honorific: getRandom(honorifics),
            full_name: `${getRandom(firstNames)} ${getRandom(lastNames)}`,
            relation: Math.random() > 0.5 ? getRandom(relations) : '',
            business_name: Math.random() > 0.7 ? `${getRandom(lastNames)} Enterprises` : '',
            category: Math.random() > 0.3 ? getRandom(categories) : '',
            phone_1: getRandomPhone(),
            phone_2: Math.random() > 0.6 ? getRandomPhone() : '',
            door_flat_no: Math.floor(Math.random() * 900) + 100 + ' A',
            street: 'Main Road',
            landmark: 'Near Temple',
            village_town: loc.city,
            mandal: Math.random() > 0.4 ? getRandom(mandals) : '',
            district: loc.district,
            state: loc.state,
            pincode: (Math.floor(Math.random() * 900000) + 100000).toString(),
            notes: 'Autogenerated mock data.'
        };
        newContacts.push(contact);
    }

    console.log('3. Inserting Contacts into Database...');
    await Contact.insertMany(newContacts);
    console.log(`✅ Successfully injected ${newContacts.length} realistic contacts.\n`);

    await mongoose.disconnect();
    console.log('Done.');
}

seedContacts().catch(err => {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
});
